//v162 Copyright (c) 2008-2019 33Across Inc. All Rights Reserved

Tynt=window.Tynt||[];
(function(){var f=window,l=document,g={distro:"IDS",id:"IDS-"+(new Date).getTime()};Tynt.IDSL=!0;Date.now||(Date.now=function(){return(new Date).getTime()});var d={_maxRef:600,_idMacro:"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",init:function(){this._icUrl=g.protocol+(Tynt.e||"")+"ic.tynt.com";this._debUrl=g.protocol+(Tynt.e||"")+"de.tynt.com/deb/v2";this._sicUrl=g.protocol+(Tynt.e||"")+"cdn-sic.33across.com/1/javascripts/sic.js";this._apUrl=g.protocol+(Tynt.e||"")+"cdn-ap.33across.com/javascripts/ap.js"},newEle:function(a,
b,c,e){e=e||window;a=e.document.createElement(a);b&&this.extend(a,b);c&&this.extend(a.style,c);return a},injectScript:function(a,b,c){b=b||window;a=this.newEle("script",{async:"async",referrerPolicy:"unsafe-url",type:"text/javascript",src:a},null,b);this.insertEle(a,c||b.document.getElementsByTagName("script")[0])},injectSicScript:function(a){this.injectScript(this._sicUrl,window,a)},injectApolloScript:function(){this.injectScript(this._apUrl)},injectSicIframe:function(a,b,c){var e={width:a.width+
"px",height:a.height+"px",border:"0 none",margin:"0"};c&&this.extend(e,c);c=this.newEle("iframe",{referrerPolicy:"unsafe-url",src:"about:blank",frameBorder:"0",frameSpacing:"0",scrolling:"no"},e);this.insertEle(c,b);a.iframeId=this.eleId(c);a.sicWindow=c.contentWindow;a=c.contentWindow.document;a.open();a.write('<!DOCTYPE html><html><head><style type="text/css">*{margin:0;padding:0;}</style></head><body><script type="text/javascript">window.Tynt = window.parent.Tynt;\x3c/script><script type="text/javascript" src="'+
this._sicUrl+'">\x3c/script></body></html>');a.close()},insertEle:function(a,b){b?"script"==b.tagName.toLowerCase()?b.parentNode.insertBefore(a,b):b.appendChild(a):document.body.appendChild(a)},eleId:function(a){var b=a.id;b||(b="x33x"+Date.now(),a.id=b);return b},_imgs:[],injectPixel:function(a,b,c){var e;try{e=l.createElement("img")}catch(k){e=document.createElement("img")}e&&(this._imgs.push(e),b&&(e.onload=b),c&&(e.onerror=c),e.referrerPolicy="unsafe-url",e.src=a)},docUrl:function(){var a=this.getLink("canonical");
a||(a=this.getMeta("property","og:url","name","original-source"));if(a){if(0!=a.indexOf("http")){var b=g.protocol+f.location.host+f.location.pathname,c=l.getElementsByTagName("base")[0];c&&(c=c.getAttribute("href"))&&(b=c);"/"==a.charAt(0)?(c=b.indexOf("/",9),-1<c&&(b=b.slice(0,c))):(c=b.lastIndexOf("/"),b=9<c?b.slice(0,c+1):b+"/");a=b+a}return a}return""},getMeta:function(a,b,c,e){var k,d=null,f=null,h=l.getElementsByTagName("meta");for(k=0;k<h.length;++k)d||h[k].getAttribute(a)!==b?c&&!f&&h[k].getAttribute(c)===
e&&(f=h[k].getAttribute("content")||null):d=h[k].getAttribute("content")||null;return d||f},getLink:function(a,b){var c,e,d=l.getElementsByTagName("link");for(c=0;c<d.length;++c)if(e=d[c].getAttribute("rel"),d[c].getAttribute("href")&&e&&(!b&&0<=e.indexOf(a)||b&&e==a))return d[c].href;return null},extend:function(a,b){var c,e;for(c=1;c<arguments.length;++c)for(e in arguments[c])arguments[c].hasOwnProperty(e)&&(a[e]=arguments[c][e]);return a},isArray:function(a){return"undefined"!=typeof a&&"[object Array]"===
Object.prototype.toString.call(a)},inArray:function(a,b){return 0<=this.indexOf(a,b)},toArray:function(a,b){return Array.prototype.slice.call(a,b||0)},indexOf:function(a,b){if(a.indexOf)return a.indexOf(b);for(var c=0;c<a.length;++c)if(a[c]===b)return c;return-1},unique:function(a){var b,c={},e=[];for(b=0;b<a.length;++b)c[a[b]]||(c[a[b]]=!0,e.push(a[b]));return e},iframeType:function(){var a=this.iframeEle(),b=x,c=", iso:"+this.isolated();if(a)a.id&&0<=a.id.search(/google_ads?_i?frame/)?(b=6,d.clog("In same-origin iframe from DFP"+
c)):(b=y,d.clog("In same-origin iframe"+c));else try{window!=window.top?"undefined"!=typeof window.$sf?(b=z,d.clog("In SafeFrame")):(b=t,d.clog("In cross-origin iframe")):d.clog("In top window")}catch(e){b=t,d.clog("iframeType: "+e.message)}return b},iframeEle:function(a){var b=null;a=a||window;try{b=a.frameElement}catch(c){}return b},iframeTop:function(){var a=window,b=null;try{for(;a!=window.top;)b=a,a=a.parent}catch(c){return null}return b?this.iframeEle(b):null},getTopWin:function(){var a=window;
try{for(;a.parent!==a&&a.parent.document;)a=a.parent}catch(b){}return a},isolated:function(){var a=!0;try{"function"==typeof window.top.open&&(a=!1)}catch(b){}return a},tyntIds:function(){return this.unique(Tynt).join("~")},getPubId:function(){for(var a=null,b=0;b<Tynt.length;++b)if("string"==typeof Tynt[b]&&22==Tynt[b].length&&0>Tynt[b].indexOf("!")){a=Tynt[b];break}return a},countIds:function(a){var b,c=0;for(b=0;b<Tynt.length;++b)Tynt[b]===a&&++c;return c},_log:function(a){"undefined"==typeof Tynt.debug&&
0<f.location.search.indexOf("__tcdebugmode=1")&&f.console&&f.console.log&&(Tynt.debug=!0);if(!0===Tynt.debug||1===Tynt.debug)a.unshift("[TC]"),f.console.log.apply(f.console,a)},log:function(){g.inXOIframe()?this.clog.apply(this,arguments):this._log(this.toArray(arguments))},clog:function(){var a=this.toArray(arguments);a.unshift(g.id);this._log(a)},callIc:function(){var a,b,c,e,k,m,n,h;if(!f._33Across.state.icDone){f._33Across.state.icDone=B;b=this.getCookie(l.cookie,"tracertraffic");a=f.location.hash;
a=/tynt=/.test(a)?a.match(/tynt=?([^?&$#]*)/)[1]:!1;e=c=this._icUrl+"/b/p?id="+this.tyntIds()+(b?"&et="+b:"")+(a?"&a="+a:"")+("string"==typeof Tynt.b?"&b="+Tynt.b:"")+"&lm="+g.type+"&ts="+Date.now()+"&dn="+g.distro+"&iso="+(this.isolated()?"1":"0")+(null==u.uspString?"":"&us_privacy="+u.uspString);(a=this.getMeta("property","og:image:url","property","og:image"))&&(e+="&img="+encodeURIComponent(this.trunc(a,250)));k=e;(a=this.getMeta("property","og:title"))&&a!=l.title&&(k+="&ct="+encodeURIComponent(this.trunc(a,
200)));m=k;l.referrer&&(a=this.trunc(l.referrer,this._maxRef),m+="&r="+encodeURIComponent(a));n=m;if(a=l.title||f.location.hostname)a=this.trim(this.trunc(a,200)),n+="&t="+encodeURIComponent(a);h=n;if(a=this.docUrl())a=this.trunc(a,400),h+="&cu="+encodeURIComponent(a);b=h;if(a=this.getLink("amphtml",!0))a=this.trunc(a,250),b+="&ah="+encodeURIComponent(a);d.callIc.rsp=function(){f._33Across.state.icDone=v};d.clog("Calling IC");this.injectPixel(b,d.callIc.rsp,function(){d.injectPixel(h,d.callIc.rsp,
function(){d.injectPixel(n,d.callIc.rsp,function(){d.injectPixel(m,d.callIc.rsp,function(){d.injectPixel(k,d.callIc.rsp,function(){d.injectPixel(e,d.callIc.rsp,function(){d.injectPixel(c,d.callIc.rsp)})})})})})})}},callDeb:function(a,b,c){function e(a,b){d.clog("Calling DEB "+b+(a?"":" on IC timeout"));var c=encodeURIComponent(d.trunc(l.referrer,d._maxRef));d.injectScript(d._debUrl+"?id="+d.tyntIds()+"&dn="+g.distro+"&cc="+b+"&r="+c,f)}"undefined"==typeof a&&(a=1);f._33Across.state.deDone>=a||(++f._33Across.state.deDone,
1!==f._33Across.state.deDone&&!0!==c||this.when(function(){return f._33Across.state.icDone==v},e,{timeout:300,timeoutCallback:e,callbackData:f._33Across.state.deDone},this),b&&0<b.length&&setTimeout(function(){d.callDeb(a,b,!0)},b.shift()))},callDebX:function(a,b){function c(a,c){d[b?"log":"clog"]("Calling DEBx "+c+(a?"":" on IC timeout"));var m=encodeURIComponent(d.trunc(l.referrer,d._maxRef)),n=w.consentString?"&gdpr_consent="+w.consentString:"";d.injectScript(d._debUrl+"?m=xch&id="+d.tyntIds()+
"&dn="+g.distro+"&cc="+c+"&r="+m+n,f)}a||(a=10);f._33Across.state.dxDone>=a||(++f._33Across.state.dxDone,this.when(function(){return f._33Across.state.icDone==v},c,{timeout:300,timeoutCallback:c,callbackData:f._33Across.state.dxDone},this))},jsonDecode:function(a){if("function"!=typeof Array.prototype.toJSON)return JSON.stringify(a);var b=Array.prototype.toJSON;delete Array.prototype.toJSON;a=JSON.stringify(a);Array.prototype.toJSON=b;return a},getCookie:function(a,b){for(var c=b+"=",e=a.split(";"),
d=0;d<e.length;d++){for(var f=e[d];" "==f.charAt(0);)f=f.substring(1,f.length);if(0==f.indexOf(c))return f.substring(c.length,f.length)}return null},trim:function(a){return a.replace(/^\s+|\s+$/g,"")},trunc:function(a,b){var c,e;if(!a||a.length<=b)return a;c=a.substring(0,b);for(e=1;3>=e;++e)if("%"==c.charAt(c.length-e))return c.substring(0,c.length-e);return c},when:function(a,b,c,e){var d,m,g,h=null,A=null,p=a();c=c||{};d=c.interval||50;m=c.timeout;g=c.timeoutCallback||function(){};if(p)return b.call(e,
p,c.callbackData),!0;h=f.setInterval(function(){if(p=a())f.clearInterval(h),f.clearTimeout(A),b.call(e,p,c.callbackData)},d);m&&(A=f.setTimeout(function(){f.clearInterval(h);g.call(e,p,c.callbackData)},m));return!1},prob:function(a){a=parseFloat(a)||0;return Math.random()<a},on:function(a,b,c,d){a.addEventListener?a.addEventListener(b,c,d||!1):a.attachEvent&&a.attachEvent("on"+b,c)},off:function(a,b,c,d){a.removeEventListener?a.removeEventListener(b,c,d||!1):a.detachEvent&&a.detachEvent("on"+b,c)}},
w={consentString:null,init:function(){var a=this,b=function(){for(var a=window,b;!b;){try{a.frames.__cmpLocator&&(b=a)}catch(c){}if(a===window.top)break;a=a.parent}var e={};f.__cmp=function(a,c,d){if(b){var f=Math.random()+"";a={__cmpCall:{command:a,parameter:c,callId:f}};e[f]=d;b.postMessage(a,"*")}else d({msg:"CMP not found"},!1)};d.on(window,"message",function(a){var b=a.data;if("string"===typeof a.data)try{b=JSON.parse(a.data)}catch(c){}b.__cmpReturn&&(a=b.__cmpReturn,e[a.callId](a.returnValue,
a.success),delete e[a.callId])},!1)},c=function(){f.__cmp("getConsentData",null,function(b,c){c&&(a.consentString=b.consentData)})};f.__cmp||b();try{c()}catch(e){b(),c()}Tynt.getConsentString=function(){return a.consentString}}},u={uspString:null,init:function(){var a=this,b=function(){for(var a=window,b;!b;){try{a.frames.__uspapiLocator&&(b=a)}catch(c){}if(a===window.top)break;a=a.parent}var e={};f.__uspapi=function(a,c,d){if(b){var f="usp-"+Math.random();a={__uspapiCall:{command:a,callId:f,version:c}};
e[f]=d;b.postMessage(a,"*")}else d({msg:"__uspapi not found"},!1)};d.on(window,"message",function(a){var b=a.data;if("string"===typeof a.data)try{b=JSON.parse(a.data)}catch(c){}b.__uspapiReturn&&(a=b.__uspapiReturn,e[a.callId](a.returnValue,a.success),delete e[a.callId])},!1)},c=function(){f.__uspapi("getUSPData",1,function(b,c){c&&(a.uspString=b.uspString)})};f.__uspapi||b();try{c()}catch(e){b(),c()}Tynt.getUspString=function(){return a.uspString}}},B=1,v=2,x=0,t=3,z=4,y=5;g.type=0;g.inIframe=function(){return this.type>
x};g.inSOIframe=function(){return this.type>=y&&6>=this.type};g.inXOIframe=function(){return this.type>=t&&this.type<=z};g.init=function(){this.type=d.iframeType();this.inSOIframe()&&(f=d.getTopWin(),l=f.document);f._33Across||(f._33Across={});f._33Across.state||(f._33Across.state={icDone:0,deDone:0,dxDone:0,ivDone:!1});this.protocol="https://";d.init();w.init();u.init();this.isolated=d.isolated();f._33Across.pvTs||(f._33Across.pvTs=Date.now())};g.init();if(g.inXOIframe())d.clog("cross-origin iframes are not supported");
else{d.callIc();var q=new Date,r;r=q.getHours();q=q.getDay();r=1<=q&&5>=q&&8<=r&&18>=r?1:20;d.callDeb(null==d.getPubId()?r:1,null,!0)}})();
